In [1]:
# Matrix Operations Assignment
import numpy as np

# Mapping letters to numbers
letter_to_number = {
    'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5,
    'f': 6, 'g': 7, 'h': 8, 'i': 9, 'j': 10,
    'k': 11, 'l': 12, 'm': 13, 'n': 14, 'o': 15,
    'p': 16, 'q': 17, 'r': 18, 's': 19, 't': 20,
    'u': 21, 'v': 22, 'w': 23, 'x': 24, 'y': 25, 'z': 26
}

# 1.a.i. 1st Matrix
initials = ['s', 'm', 's']  # SMS
second_letters = ['h', 'a', 'u']  # HAU

first_row = [letter_to_number[char.lower()] for char in initials]
second_row = [letter_to_number[char.lower()] for char in second_letters]

matrix1 = np.array([first_row, second_row])

# 1.a.ii. 2nd Matrix
student_first3 = [2, 0, 2]  # From 2023
student_last3 = [1, 3, 8]   # From 0138

matrix2 = np.array([student_first3, student_last3])

# 1.b. Print both matrices
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)

# 2. Matrix Addition
matrix3 = matrix1 + matrix2
print("\nMatrix 3 (Matrix 1 + Matrix 2):")
print(matrix3)

# 3. Scalar Multiplication
matrix4 = 2 * matrix1
print("\nMatrix 4 (Matrix 1 multiplied by 2):")
print(matrix4)

# 4. Matrix Transpose
matrix5 = matrix2.T
print("\nMatrix 5 (Transpose of Matrix 2):")
print(matrix5)

# 5. Matrix Multiplication
matrix6 = np.matmul(matrix3, matrix5)
print("\nMatrix 6 (Matrix 3 multiplied by Matrix 5):")
print(matrix6)

# 6. Sum of All Elements in Matrix 3
sum_matrix3 = np.sum(matrix3)
print("\nSum of all elements in Matrix 3:", sum_matrix3)

# 7. Zero Matrix
matrix7 = np.zeros((2, 3), dtype=int)
print("\nMatrix 7 (2x3 Zero Matrix):")
print(matrix7)


Matrix 1:
[[19 13 19]
 [ 8  1 21]]

Matrix 2:
[[2 0 2]
 [1 3 8]]

Matrix 3 (Matrix 1 + Matrix 2):
[[21 13 21]
 [ 9  4 29]]

Matrix 4 (Matrix 1 multiplied by 2):
[[38 26 38]
 [16  2 42]]

Matrix 5 (Transpose of Matrix 2):
[[2 1]
 [0 3]
 [2 8]]

Matrix 6 (Matrix 3 multiplied by Matrix 5):
[[ 84 228]
 [ 76 253]]

Sum of all elements in Matrix 3: 97

Matrix 7 (2x3 Zero Matrix):
[[0 0 0]
 [0 0 0]]
